import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {AlertCircle,ArrowRight,ArrowUpRight,Check,CheckCircle2,Database,FileJson,FileText,Loader2,RefreshCw,Search,Terminal,Upload,X} from 'lucide-react';
import {api,warningNames,type ImportResult} from './api';
import type {Capabilities} from './diagnosis';
import {useData} from './read-data';
import './onboarding-pages.css';

function ErrorNotice({error,retry,retained=false}:{error:string;retry?:()=>void;retained?:boolean}){return error?<div className="setup-error" role="alert"><AlertCircle size={15}/><span>{retained?'更新失败，保留上次记录。 ':''}{error}</span>{retry&&<button onClick={retry}>重试</button>}</div>:null;}
function Source({kind}:{kind:string}){return <span className="source-tag">{({synthetic:'合成演示',derived:'派生样例',historical:'历史实验'} as Record<string,string>)[kind]||'来源未声明'}</span>;}
type ManifestPreview={goal?:string;task_id?:string;sample_kind?:string;runs?:{run_key?:string;attempt_index?:number;telemetry?:string;report?:string;outcome?:string;feedback?:string}[]};
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1024*1024?`${(bytes/1024).toFixed(1)} KiB`:`${(bytes/1024/1024).toFixed(1)} MiB`;

export function ImportsPage(){
  const [refresh,setRefresh]=useState(0),history=useData<ImportResult[]>('/imports',refresh);
  const [manifest,setManifest]=useState<File|null>(null),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ImportResult|null>(null),[preview,setPreview]=useState<ManifestPreview|null>(null),[previewError,setPreviewError]=useState(''),[query,setQuery]=useState('');
  const fileInput=useRef<HTMLInputElement>(null),manifestInput=useRef<HTMLInputElement>(null),resultRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{let cancelled=false;setPreview(null);setPreviewError('');if(manifest){if(manifest.size>128*1024)setPreviewError('清单超过 128 KiB，服务端会拒绝导入。');else manifest.text().then(text=>{try{const value=JSON.parse(text.replace(/^\uFEFF/,''));if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();if(!cancelled)setPreview(value);}catch{if(!cancelled)setPreviewError('清单不是可读取的 JSON；请检查格式后重新选择。');}}).catch(()=>{if(!cancelled)setPreviewError('无法读取清单文件，请重新选择。');});}return()=>{cancelled=true};},[manifest]);
  useEffect(()=>{if(result)resultRef.current?.focus({preventScroll:false});},[result]);
  const runs=Array.isArray(preview?.runs)?preview.runs:[];
  const references=[...new Set(runs.flatMap(run=>run&&typeof run==='object'?['telemetry','report','outcome','feedback'].map(key=>run[key as keyof typeof run]).filter((value):value is string=>typeof value==='string'&&!!value):[]))];
  const missing=references.filter(name=>!files.some(file=>file.name===name));
  const duplicateNames=files.filter((file,index)=>files.findIndex(other=>other.name===file.name)!==index).map(file=>file.name);
  const oversized=files.filter(file=>file.size>10*1024*1024);
  // Only file transport constraints are prechecked; schema/semantics remain server-authoritative.
  const fileError=files.length>40?'一次导入最多 40 个文件。':duplicateNames.length?'文件名重复：'+duplicateNames.join('、'):oversized.length?'文件超过 10 MiB：'+oversized.map(f=>f.name).join('、'):'';
  function edited(){setError('');setResult(null);}
  async function submit(event:FormEvent){event.preventDefault();if(!manifest||!files.length||busy)return;setBusy(true);setError('');setResult(null);try{const body=new FormData();body.append('manifest',manifest);files.forEach(file=>body.append('files',file));setResult(await api<ImportResult>('/imports',{method:'POST',body}));setRefresh(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const visible=(history.data||[]).filter(item=>`${item.manifest.task_id} ${item.manifest.source_namespace}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="setup-page imports-page"><div className="page-heading"><div><h1>导入记录</h1><p>把已有执行记录带入工作台，保留原件、轮次与检查来源。</p></div><Link className="setup-button" to="/?start=monitor"><Terminal size={15}/>接入实时 Agent</Link></div>
    <div className="setup-import-layout"><form onSubmit={submit} className="setup-import-form" aria-busy={busy}><div className="setup-step-head"><span>1</span><div><h2>选择导入清单</h2><p>清单说明任务与每轮使用的文件，不执行其中的命令。</p></div><span className={'setup-ready '+(manifest?'ready':'')}>{manifest?<><Check size={13}/>已选择</>:'待选择'}</span></div>
      <div className="setup-file-control"><FileJson size={21}/><div><strong>{manifest?.name||'manifest.json'}</strong><small>{manifest?size(manifest.size):'JSON · 最大 128 KiB'}</small></div><label className="setup-button">{manifest?'更换清单':'选择清单'}<input ref={manifestInput} aria-label="导入清单" type="file" accept=".json" disabled={busy} onChange={e=>{setManifest(e.target.files?.[0]||null);edited();}}/></label>{manifest&&<button type="button" className="setup-icon" aria-label="移除导入清单" disabled={busy} onClick={()=>{setManifest(null);if(manifestInput.current)manifestInput.current.value='';edited();}}><X size={16}/></button>}</div>
      {preview&&<div className="setup-manifest-preview"><strong>{typeof preview.goal==='string'?preview.goal:'未提供任务目标'}</strong><span>{runs.length} 轮执行 · {references.length} 个引用文件 · <Source kind={typeof preview.sample_kind==='string'?preview.sample_kind:'historical'}/></span><details><summary>清单中的轮次与文件</summary>{runs.map((run,index)=><div key={index}><strong>第 {typeof run?.attempt_index==='number'?run.attempt_index:'?'} 次</strong><code>{typeof run?.run_key==='string'?run.run_key:'未提供 run_key'}</code><span>{run&&typeof run==='object'?['telemetry','report','outcome','feedback'].map(key=>run[key as keyof typeof run]).filter(value=>typeof value==='string').join(' · '):'轮次字段需要服务端校验'}</span></div>)}</details></div>}
      <ErrorNotice error={previewError}/>
      <div className="setup-step-head"><span>2</span><div><h2>添加数据文件</h2><p>轨迹、报告、检查结果；文件名与清单引用一致。</p></div><span className={'setup-ready '+(files.length&&!missing.length&&!fileError?'ready':'')}>{files.length?`${files.length} 个已选`:'待添加'}</span></div>
      <div className="setup-file-control"><Upload size={21}/><div><strong>选择清单引用的原始文件</strong><small>JSONL / JSON / Markdown / TXT · 最多 40 个 · 单文件 10 MiB</small></div><label className="setup-button">添加文件<input ref={fileInput} aria-label="数据文件" type="file" multiple accept=".json,.jsonl,.md,.txt" disabled={busy} onChange={e=>{const added=Array.from(e.target.files||[]);setFiles(old=>[...old,...added]);e.target.value='';edited();}}/></label></div>
      {files.length>0&&<div className="setup-file-list">{files.map((file,index)=><div key={index}><FileText size={14}/><span title={file.name}>{file.name}</span><small>{size(file.size)}</small><button type="button" className="setup-icon" aria-label={'移除文件 '+file.name} disabled={busy} onClick={()=>{setFiles(old=>old.filter((_,i)=>i!==index));edited();}}><X size={14}/></button></div>)}</div>}
      {missing.length>0&&<p className="setup-file-warning">尚未选中清单引用：{missing.join('、')}</p>}<ErrorNotice error={fileError}/><ErrorNotice error={error}/>
      <div className="setup-submit"><div><strong>{busy?'正在校验并保存…':result?'导入结果已返回':manifest&&files.length?'文件已选择，等待服务端校验':'准备清单与原始文件'}</strong><small>预览只检查文件准备情况；最终以导入校验为准。</small></div><button className="button primary" disabled={!manifest||!files.length||busy||!!fileError||!!previewError}>{busy?<Loader2 size={16} className="spin"/>:<ArrowRight size={16}/>} {busy?'校验并导入中…':'校验并导入'}</button></div>
      {result&&<div className="setup-result" ref={resultRef} tabIndex={-1} role="status"><CheckCircle2 size={22}/><div><strong>{result.duplicate?'记录已存在，未重复导入':'导入完成'}</strong><p>{result.run_ids.length} 轮执行 · 历史导入 · {result.warnings.length} 项数据提示</p><Link className="setup-link" to={result.run_ids.length===1?'/runs/'+result.run_ids[0]:'/tasks/'+result.task_id}>{result.run_ids.length===1?'打开运行':'打开任务'}<ArrowRight size={14}/></Link>{result.warnings.length>0&&<details><summary>查看数据提示</summary><ul>{result.warnings.map((warning,index)=><li key={index}>{warningNames[warning]||warning}</li>)}</ul></details>}</div></div>}
    </form><aside className="setup-guide"><h2>导入后可以做什么？</h2><ul><li><FileSearchIcon/><div><strong>回看执行过程</strong><p>原始事件进入 Run，证据可以回到原件。</p></div></li><li><Search size={18}/><div><strong>查看或手动发起分析</strong><p>历史报告与本次诊断分别保留；不会自动调用模型。</p></div></li><li><CheckCircle2 size={18}/><div><strong>核对任务检查</strong><p>执行完成、原因分析与检查结果独立记录。</p></div></li></ul><details><summary>清单与轮次规则</summary><p>一份清单对应一个任务，每轮使用独立 run_key 与 attempt_index。同一轮内容变化会被拒绝，重复导入不会覆盖历史。</p><p>不要上传密钥、模型权重或 provenance.local.json。</p><a className="setup-link" href="/api/contracts/import-manifest" target="_blank" rel="noreferrer">查看清单 JSON Schema<ArrowUpRight size={13}/></a></details><Link className="setup-link" to="/system">检查运行环境<ArrowUpRight size={13}/></Link></aside></div>
    <section className="setup-history"><header><h2>最近导入</h2><label className="setup-search"><Search size={15}/><input aria-label="搜索导入记录" placeholder="搜索任务或来源…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空导入搜索" onClick={()=>setQuery('')}><X size={14}/></button>}</label><small>最多 100 次</small><button className="setup-button" disabled={history.loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={14}/>刷新</button></header><ErrorNotice error={history.error} retry={()=>setRefresh(v=>v+1)} retained={!!history.data}/>
      {history.loading&&!history.data?<p className="setup-empty" role="status">正在读取导入记录…</p>:history.data&&!visible.length?<div className="setup-empty"><FileText size={22}/><strong>{query?'没有匹配的导入记录':'还没有导入记录'}</strong><span>{query?'尝试其他任务名或来源。':'选择清单和原始文件，完成第一次导入。'}</span>{query&&<button className="setup-link" onClick={()=>setQuery('')}>清空搜索</button>}</div>:visible.map(item=><div className="setup-history-row" key={item.import_id}><FileText size={17}/><div><Link to={'/tasks/'+item.task_id}>{item.manifest.task_id}</Link><small>{item.manifest.source_namespace} · {item.run_ids.length} 轮 · {new Date(item.created_at).toLocaleString('zh-CN')}</small></div><Source kind={item.manifest.sample_kind}/><Link className="setup-icon" aria-label="查看导入任务" to={'/tasks/'+item.task_id}><ArrowUpRight size={17}/></Link></div>)}
    </section></div>;
}
function FileSearchIcon(){return <FileJson size={18}/>;}

export function SystemPage(){
  const [refresh,setRefresh]=useState(0),health=useData<{version:string;status:string}>('/health',refresh),caps=useData<Capabilities>('/diagnosis/capabilities',refresh);
  const analyst=caps.data?.analyst;
  const analystLabel=({configured:'已配置 · 尚未调用',last_call_succeeded:'最近调用成功',last_call_failed:'最近调用失败',unconfigured:'未配置',disabled:'已禁用'} as Record<string,string>)[analyst||'']||'配置状态未知';
  const hgt=caps.data?.hgt;
  return <div className="setup-page system-page"><div className="page-heading"><div><h1>运行环境</h1><p>核对平台连接与分析条件，再在终端启动 Agent。</p></div><button className="setup-button" disabled={health.loading||caps.loading} onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={14}/>刷新状态</button></div>
    <div className="setup-environment-header"><Database size={21}/><div><strong>本地工作区</strong><span>{health.data?`平台 ${health.data.version}`:'等待版本信息'} · SQLite 本地存储</span></div><Link className="button primary" to="/?start=monitor"><Terminal size={15}/>开始监控</Link></div>
    <ErrorNotice error={health.error} retry={()=>setRefresh(v=>v+1)} retained={!!health.data}/><ErrorNotice error={caps.error} retry={()=>setRefresh(v=>v+1)} retained={!!caps.data}/>
    <section className="setup-capabilities" aria-label="环境能力"><div className="setup-capability"><Database size={20}/><div><h2>平台 API</h2><p>用于事件上报、页面读取与实时更新；在线不代表 Agent 已接入。</p></div><span className={'setup-status '+(!health.error&&health.data?.status==='ok'?'ready':'unknown')}>{health.error?'当前连接失败':health.loading?'正在读取…':health.data?.status==='ok'?'已连接':health.data?'状态 '+health.data.status:'连接未知'}</span></div>
      <div className="setup-capability"><Terminal size={20}/><div><h2>Agent 采集</h2><p>使用 Python CLI / SDK 或已有适配器。实际收到的工具、用量与检查记录在首页“接入反馈”核对。</p><Link className="setup-link" to="/?start=monitor">查看接入步骤<ArrowUpRight size={13}/></Link></div><span className="setup-status available">提供接入方式</span></div>
      <div className="setup-capability"><Search size={20}/><div><h2>异常步骤定位 <small>本机</small></h2><p>从已有工具调用与返回中定位异常线索，不调用原因分析模型。当前状态沿用环境检查记录。</p></div><span className={'setup-status '+(caps.error?'unknown':hgt==='ready'?'ready':'unknown')}>{caps.error?'当前状态无法读取':caps.loading?'正在读取…':hgt==='ready'?'已就绪':hgt==='unverified'?'尚未验证':hgt==='unavailable'?'未配置':'状态未知'}</span></div>
      <div className="setup-capability"><Search size={20}/><div><h2>原因分析 <small>RCA · 模型</small></h2><p>{caps.data?.model?`配置模型：${caps.data.model}。`:'尚无已读取的模型配置。'}必须先预览发送内容，再人工确认调用；配置状态不保证下一次调用成功。</p><Link className="setup-link" to="/settings/models">管理模型连接<ArrowUpRight size={13}/></Link></div><span className={'setup-status '+(caps.error?'unknown':analyst==='last_call_failed'?'failed':analyst==='last_call_succeeded'?'ready':analyst==='configured'?'available':'unknown')}>{caps.error?'当前状态无法读取':caps.loading?'正在读取…':analystLabel}</span></div></section>
    <section className="setup-next"><div><h2>下一步</h2><p>接入后，回到运行工作台确认事件是否到达。分析与检查都在对应 Run 内查看。</p></div><Link className="setup-button" to="/">查看接入反馈<ArrowRight size={14}/></Link><Link className="setup-button" to="/imports">导入历史记录<ArrowRight size={14}/></Link></section>
    <details className="setup-technical"><summary>状态口径与技术信息</summary><dl><dt>API 状态</dt><dd>{health.data?.status||'未读取'}</dd><dt>平台版本</dt><dd>{health.data?.version||'未读取'}</dd><dt>HGT 状态</dt><dd>{hgt||'未读取'}</dd><dt>模型配置状态</dt><dd>{analyst||'未读取'}</dd><dt>定位环境记录</dt><dd>{caps.data?.reason||'未读取'}</dd></dl><p>环境页读取现有能力记录，不测试模型连接、不执行 HGT、不启动 Agent。导入历史报告也不触发新的推理。</p></details>
  </div>;
}
