import {useEffect,useState,type ReactNode} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {AlertCircle,ArrowLeft,ArrowRight,ArrowUpRight,ArrowLeftRight,Check,FileSearch,GitCompareArrows,RefreshCw} from 'lucide-react';
import {api,pretty,type Outcome,type Run,type Task} from './api';
import {Fact} from './task-history';
import './run-comparison.css';

function Capture({run}:{run:Run}){const value=run.capture_integrity||'unknown';return <span className={'comparison-capture '+value}>{value==='partial'?<AlertCircle size={14}/>:value==='complete'?<Check size={14}/>:null}{({complete:'采集完整',partial:'采集不完整',pending:'待补齐',unknown:'采集情况未知'} as Record<string,string>)[value]||'采集情况未知'}{run.dropped_events?` · 丢失 ${run.dropped_events}`:''}</span>;}
function Checks({run,onEvidence}:{run:Run;onEvidence:(id:string)=>void}){
  const [records,setRecords]=useState<Outcome[]|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  useEffect(()=>{const controller=new AbortController();setRecords(null);setError('');api<Outcome[]>('/runs/'+run.run_id+'/outcomes',{signal:controller.signal}).then(setRecords).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[run.run_id,refresh]);
  return <div className="comparison-checks">{error?<p role="alert">无法读取检查记录。{error} <button onClick={()=>setRefresh(v=>v+1)}>重试</button></p>:records===null?<p className="comparison-muted" role="status">读取检查依据…</p>:!records.length?<p className="comparison-muted">未提供独立检查记录；执行完成不能代替任务通过。</p>:records.map(item=><div key={item.outcome_id} className="comparison-check"><span className={'comparison-outcome '+item.status}>{({passed:'验收通过',failed:'验收未通过',unknown:'验收未知'} as Record<string,string>)[item.status]||'验收未知'}</span><strong>{item.source||'来源未声明'}</strong>{!item.authoritative&&<small>非最终检查来源</small>}<p>{item.summary||'来源未提供摘要'}</p><details><summary>检查依据与原始记录</summary><pre>{pretty(item.basis)}</pre><button className="comparison-link" onClick={()=>onEvidence(item.evidence_id)}>查看原始检查记录<ArrowUpRight size={13}/></button></details></div>)}</div>;
}
function Detail({run,source,onEvidence}:{run:Run;source:ReactNode;onEvidence:(id:string)=>void}){
  const report=run.insight?.diagnosis.featured_report,signals=run.insight?.failure_signals||[];
  return <section className="comparison-run-detail"><header><strong>第 {run.attempt_index} 次运行</strong><Link className="comparison-link" to={'/runs/'+run.run_id}>查看运行详情<ArrowUpRight size={14}/></Link></header><div className="comparison-source">{source}<small title={run.created_at}>入库 {new Date(run.created_at).toLocaleString('zh-CN')}</small></div>
    <h3>任务检查与依据</h3><Checks run={run} onEvidence={onEvidence}/>
    <h3>失败线索 <small>{signals.length} 条</small></h3>{signals.length?signals.map((signal,index)=><div className="comparison-signal" key={index}><AlertCircle size={15}/><div><strong>{signal.title}</strong><div>{signal.evidence_id&&<button className="comparison-link" onClick={()=>onEvidence(signal.evidence_id!)}>查看证据</button>}{signal.event_id&&<Link className="comparison-link" to={`/runs/${run.run_id}?event=${encodeURIComponent(signal.event_id)}`}>定位事件<ArrowUpRight size={12}/></Link>}</div></div></div>):<p className="comparison-muted">当前记录中没有明确失败线索。</p>}
    <h3>原因分析</h3><Fact kind="diagnosis" run={run}/>{report&&<div className="comparison-hypothesis"><p className="comparison-excerpt">{report.summary}</p><details><summary>展开来源摘要</summary><p>{report.summary}</p></details><small>{report.kind==='hypothesis'?'根因假设待验证':report.kind==='localization'?'定位线索':'来源报告'} · 不改变任务检查结果</small></div>}
  </section>;
}

export function RunComparison({task,error,onRefresh,renderSource,onEvidence}:{task:Task;error:string;onRefresh:()=>void;renderSource:(run:Run)=>ReactNode;onEvidence:(id:string)=>void}){
  const location=useLocation(),navigate=useNavigate(),params=new URLSearchParams(location.search);
  const requestedLeft=params.get('left'),requestedRight=params.get('right');
  const valid=requestedLeft!==requestedRight&&task.runs.some(r=>r.run_id===requestedLeft)&&task.runs.some(r=>r.run_id===requestedRight);
  const [selection,setSelection]=useState<{left:string;right:string;search:string}>(()=>({left:valid?requestedLeft!:task.runs[0]?.run_id||'',right:valid?requestedRight!:task.runs.at(-1)?.run_id||'',search:location.search}));
  const [invalid,setInvalid]=useState(!!(requestedLeft||requestedRight)&&!valid),[onlyChanges,setOnlyChanges]=useState(false);
  useEffect(()=>{if(selection.search===location.search)return;setInvalid(!!(requestedLeft||requestedRight)&&!valid);setSelection({left:valid?requestedLeft!:task.runs[0]?.run_id||'',right:valid?requestedRight!:task.runs.at(-1)?.run_id||'',search:location.search});},[location.search,task]);
  function select(left:string,right:string){setInvalid(false);const next=new URLSearchParams({left,right}),search='?'+next.toString();setSelection({left,right,search});navigate({pathname:location.pathname,search},{replace:true});}
  const a=task.runs.find(r=>r.run_id===selection.left),b=task.runs.find(r=>r.run_id===selection.right);
  const dims=['outcome','execution','diagnosis','capture','signals'] as const;
  function value(run:Run,key:typeof dims[number]){if(key==='outcome')return run.outcome_status||'unknown';if(key==='execution')return run.execution_status||'unknown';if(key==='diagnosis'){const d=run.insight?.diagnosis;return `${d?.state||'none'}:${d?.report_count&&d.latest_job&&['failed','timed_out','interrupted'].includes(d.latest_job.state)?'latest_failed':''}`;}if(key==='capture')return `${run.capture_integrity||'unknown'}:${run.dropped_events||0}`;return String(run.insight?.failure_signals.length||0);}
  const changes=a&&b?dims.filter(key=>value(a,key)!==value(b,key)):[];
  return <div className="compare-page"><Link className="comparison-back" to={'/tasks/'+task.id}><ArrowLeft size={14}/>返回任务历程</Link><div className="page-heading"><div><h1>比较两次运行</h1><p title={task.goal}>{task.goal}</p></div><button className="comparison-button" onClick={onRefresh}><RefreshCw size={14}/>刷新</button></div>
    <div className="comparison-toolbar">{(['left','right'] as const).map((key,index)=><label key={key}><span>{index===0?'基准运行':'对照运行'}</span><select aria-label={index===0?'基准运行':'对照运行'} value={selection[key]} onChange={e=>select(key==='left'?e.target.value:selection.left,key==='right'?e.target.value:selection.right)}>{task.runs.map(run=><option key={run.run_id} value={run.run_id}>第 {run.attempt_index} 次 · {new Date(run.created_at).toLocaleString('zh-CN')}</option>)}</select></label>)}<button className="comparison-button" aria-label="交换两次运行" disabled={!a||!b||a===b} onClick={()=>select(selection.right,selection.left)}><ArrowLeftRight size={16}/><span>交换</span></button><label className="comparison-toggle"><input type="checkbox" checked={onlyChanges} onChange={e=>setOnlyChanges(e.target.checked)}/>仅看变化</label></div>
    {invalid&&<div className="notice">链接中的运行选择无效，已显示本任务的首末运行。</div>}{error&&<div className="comparison-error" role="alert">刷新失败，保留上次记录。{error}<button onClick={onRefresh}>重试</button></div>}
    {task.runs.length<2?<div className="comparison-empty"><FileSearch size={25}/><strong>暂时没有可对比的运行</strong><div className="notice">需要两次不同运行才能对比。请返回任务历程查看已有记录。</div></div>:a&&b&&a!==b?<>
      <section className="comparison" aria-label="运行事实对比"><div className="comparison-summary"><GitCompareArrows size={18}/><strong>第 {a.attempt_index} 次<ArrowRight size={14}/>第 {b.attempt_index} 次</strong><span>{changes.length} 项事实变化 / {dims.length} 项</span><small>只比较记录，不推断修复效果</small></div><table><thead><tr><th>独立事实</th><th>基准 · 第 {a.attempt_index} 次</th><th>对照 · 第 {b.attempt_index} 次</th><th>变化</th></tr></thead><tbody>{dims.filter(key=>!onlyChanges||changes.includes(key)).map(key=><tr key={key} className={changes.includes(key)?'is-changed':''}><th scope="row">{({outcome:'任务检查',execution:'执行状态',diagnosis:'原因分析',capture:'采集完整性',signals:'失败线索'})[key]}</th>{[a,b].map(run=><td key={run.run_id}>{['outcome','execution','diagnosis'].includes(key)?<Fact kind={key as 'outcome'|'execution'|'diagnosis'} run={run}/>:key==='capture'?<Capture run={run}/>:<span>{run.insight?.failure_signals.length||0} 条</span>}</td>)}<td><span className={'comparison-delta '+(changes.includes(key)?'changed':'')}>{changes.includes(key)?'有变化':key==='signals'?'数量相同':'状态相同'}</span></td></tr>)}</tbody></table>{onlyChanges&&!changes.length&&<p className="comparison-no-change">这五项事实没有变化；相同或未知状态不代表两次执行内容相同。</p>}
      <p className="comparison-boundary">执行完成 ≠ 任务通过。结果变化不能单独证明根因假设或修复有效。</p><details className="comparison-counts"><summary>辅助计数与原始标识</summary><table><tbody>{[['原始事件',a.event_count,b.event_count],['采集工具调用',a.tool_call_count,b.tool_call_count],['可靠配对',a.confirmed_pairs,b.confirmed_pairs],['失败工具返回',a.failed_tool_count,b.failed_tool_count],['Run ID',a.run_id,b.run_id]].map(([label,left,right])=><tr key={label}><th>{label}</th><td>{left??'—'}</td><td>{right??'—'}</td></tr>)}</tbody></table></details></section>
      <div className="comparison-details"><Detail key={a.run_id} run={a} source={renderSource(a)} onEvidence={onEvidence}/><Detail key={b.run_id} run={b} source={renderSource(b)} onEvidence={onEvidence}/></div>
    </>:<div className="notice">当前选择了同一次运行，请选择不同轮次。</div>}
  </div>;
}
