import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';

test('真实离线 HGT 作业、固定快照与定位证据',async({page,request})=>{
  test.setTimeout(120000);
  const capabilities=await (await request.get('/api/diagnosis/capabilities')).json();
  test.skip(capabilities.hgt!=='ready','Requires locally verified AgentTether bundle; never calls an LLM');
  const token=randomUUID()+randomUUID();
  const run=await (await request.post('/api/live/runs',{data:{request_id:randomUUID(),write_token:token,goal:'HGT synthetic browser acceptance',sample_kind:'synthetic'}})).json();
  const headers={Authorization:'Bearer '+token};
  const events=[{kind:'tool_call',input:{command:'pytest'},ok:null,output:null},{kind:'tool_return',input:null,ok:false,output:{returncode:1,stderr:'AssertionError: synthetic regression'}}].map((e,i)=>({...e,event_id:randomUUID(),producer_id:'browser-hgt',producer_seq:i+1,occurred_at:new Date().toISOString(),name:'shell',correlation_id:'shell-pair'}));
  expect((await request.post('/api/live/runs/'+run.run_id+'/events',{headers,data:{events}})).ok()).toBeTruthy();
  expect((await request.post('/api/live/runs/'+run.run_id+'/finish',{headers,data:{exit_code:0,producers:{'browser-hgt':2}}})).ok()).toBeTruthy();
  await page.goto('/runs/'+run.run_id);
  await page.getByRole('button',{name:'定位异常步骤（本机）',exact:true}).click();
  await expect(page.locator('.console-states')).toContainText('已有定位线索',{timeout:90000});
  await expect(page.locator('.analysis-result-heading')).toContainText('定位线索 · 尚非完整原因分析');
  await page.getByRole('button',{name:'更多资料',exact:true}).click();
  await page.locator('.technical-group').nth(1).locator('summary').first().click();
  await page.locator('.technical-report>summary').first().click();
  await page.getByRole('button',{name:'输入快照',exact:true}).click();
  await expect(page.getByRole('tab',{name:'原始证据',exact:true})).toHaveAttribute('aria-selected','true');
  await expect(page.locator('.source-code')).toContainText('schema_version');
  await page.keyboard.press('Escape');
  await page.getByRole('tab',{name:/^原因分析/}).click();
  await page.locator('.hypothesis-evidence .evidence-chip.resolved').first().click();
  await expect(page.locator('.source-code')).toContainText('shell');
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.locator('.analysis-result-heading')).toContainText('定位线索 · 尚非完整原因分析');
  await page.screenshot({path:'../../.local/screenshots/v03-diagnosis.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.screenshot({path:'../../.local/screenshots/v03-diagnosis-mobile.png',fullPage:true});
});
